#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d78bcobuibrs73bk0nl0-a.singapore-postgres.render.com/moneymanager_az36
spring.datasource.username=moneymanager_az36_user
spring.datasource.password=Xv65N1oeSX4xZUrFrINN4Df80L410L5z